# Generated by Django 2.0 on 2017-12-27 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Major', models.IntegerField()),
                ('Minor', models.IntegerField()),
                ('BldgNbr', models.IntegerField()),
                ('Address', models.CharField(max_length=200)),
                ('main_use', models.CharField(max_length=20)),
                ('Number_of_Stories', models.IntegerField(default=1)),
                ('Construction_Class', models.IntegerField()),
                ('Year_built', models.IntegerField()),
                ('Year_remodeled', models.IntegerField()),
                ('Heating_System', models.IntegerField()),
                ('Elevators', models.BooleanField()),
                ('Tax_PIN', models.FloatField()),
                ('No_parking_gfa', models.FloatField()),
                ('Property_Name', models.CharField(max_length=200)),
                ('Site_Energy_kbtu', models.FloatField()),
                ('Electricity_kwh', models.FloatField()),
                ('Electricity_kbtu', models.FloatField()),
                ('Natural_Gas_kbtu', models.FloatField()),
                ('Steam_kbtu', models.FloatField()),
                ('site_eui', models.FloatField()),
            ],
        ),
    ]
