# Generated by Django 2.0 on 2017-12-28 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plots', '0002_ashrae_targets'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ASHRAE_targets',
            new_name='ASHRAE_target',
        ),
    ]
